import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import '../styles/index.css'

const publicSans = Public_Sans({
	variable: '--font-public-sans',
	subsets: ['latin'],
	style: 'normal',
	display: 'swap'
})

export const metadata: Metadata = {
	title: {
		template: '%s - SQLFactory',
		default: 'SQLFactory'
	},
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={`${publicSans.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col font-public-sans">
				<div id="root" className={'bg-dark text-white'}>
					{children}
				</div>
			</body>
		</html>
	)
}
