import type { Metadata } from 'next'
import '../styles/index.css'
import { INTER } from '@/configs/fonts.config'

export const metadata: Metadata = {
	title: {
		template: '%s - SQLFactory',
		default: 'SQLFactory'
	},
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={`${INTER.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col font-inter">
				<div id="root" className={'bg-white text-dark-menu'}>
					{children}
				</div>
			</body>
		</html>
	)
}
